routes/web.php
			Route::match(array('GET', 'POST'), 'add-testimonials', 'TestimonialController@add');
			Route::match(array('GET', 'POST'), 'edit-testimonials/{id}', 'TestimonialController@update');
			Route::get('delete-testimonials/{id}', 'TestimonialController@delete');
		});
	});
});

//only can view if admin is not logged in if they are logged in then they will be redirect to dashboard
Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'no_auth:admin'], function () {
    Route::get('login', 'AdminController@login');
});

//only can view if user is not logged in if they are logged in then they will be redirect to dashboard
Route::group(['middleware' => ['no_auth:users', 'locale']], function () {
    Route::get('login', 'LoginController@index');
    Route::get('auth/login', function()
    {
		return Redirect::to('login');
    });

    Route::get('googleLogin', 'LoginController@googleLogin')->middleware('social_login:google_login');
    Route::get('facebookLogin', 'LoginController@facebookLogin')->middleware('social_login:facebook_login');
    Route::get('register', 'HomeController@register');
    Route::match(array('GET', 'POST'), 'forgot_password', 'LoginController@forgotPassword');
    Route::post('create', 'UserController@create');
    Route::post('authenticate', 'LoginController@authenticate');
    Route::get('users/reset_password/{secret?}', 'LoginController@resetPassword');
    Route::post('users/reset_password', 'LoginController@resetPassword');
});

Route::get('googleAuthenticate', 'LoginController@googleAuthenticate');
Route::get('facebookAuthenticate', 'LoginController@facebookAuthenticate');
Route::match(['get', 'post'], 'emails/contact_us', 'EmailController@contactUs')->name('contactus');


//only can view if user is logged in
Route::group(['middleware' => ['guest:users', 'locale']], function () {
    Route::get('dashboard', 'UserController@dashboard')->name('dashboard');
    Route::match(array('GET', 'POST'),'users/profile', 'UserController@profile');
    Route::match(array('GET', 'POST'),'users/profile/media', 'UserController@media');

    // User verification
    Route::get('users/edit-verification', 'UserController@verification');
    Route::get('users/confirm_email/{code?}', 'UserController@confirmEmail');
    Route::get('users/new_email_confirm', 'UserController@newConfirmEmail');

    Route::get('facebookLoginVerification', 'UserController@facebookLoginVerification');
    Route::get('facebookConnect/{id}', 'UserController@facebookConnect');
    Route::get('facebookDisconnect', 'UserController@facebookDisconnectVerification');

    Route::get('googleLoginVerification', 'UserController@googleLoginVerification');
    Route::get('googleConnect/{id}', 'UserController@googleConnect');
    Route::get('googleDisconnect', 'UserController@googleDisconnect');
    // Route::get('googleAuthenticate', 'LoginController@googleAuthenticate');

    Route::get('users/show/{id}', 'UserController@show');
	Route::match(array('GET', 'POST'),'users/reviews', 'UserController@reviews');
	Route::match(array('GET', 'POST'),'users/reviews_by_you', 'UserController@reviewsByYou');
    Route::match(['get', 'post'], 'reviews/edit/{id}', 'UserController@editReviews');
    Route::match(['get', 'post'], 'reviews/details', 'UserController@reviewDetails');

    Route::match(array('GET', 'POST'),'properties', 'PropertyController@userProperties');
    Route::match(array('GET', 'POST'),'property/create', 'PropertyController@create');
    Route::match(array('GET', 'POST'),'listing/{id}/photo_message', 'PropertyController@photoMessage')->middleware(['checkUserRoutesPermissions']);
    Route::match(array('GET', 'POST'),'listing/{id}/photo_delete', 'PropertyController@photoDelete')->middleware(['checkUserRoutesPermissions']);

	// Route::get('/contact_us', function () {
	// 	return view('emails.contact_us');
	// });

	Route::match(array('POST'),'listing/photo/make_default_photo', 'PropertyController@makeDefaultPhoto');

	Route::match(array('POST'),'listing/photo/make_photo_serial', 'PropertyController@makePhotoSerial');

    Route::match(array('GET', 'POST'),'listing/update_status', 'PropertyController@updateStatus');
    Route::match(array('GET', 'POST'),'listing/{id}/{step}', 'PropertyController@listing')->where(['id' => '[0-9]+','page' => 'basics|description|location|amenities|photos|pricing|calendar|details|booking']);

    // Favourites routes
    Route::get('user/favourite', 'PropertyController@userBookmark');
    Route::post('add-edit-book-mark', 'PropertyController@addEditBookMark');

    Route::post('ajax-calender/{id}', 'CalendarController@calenderJson');
    Route::post('ajax-calender-price/{id}', 'CalendarController@calenderPriceSet');
    //iCalendar routes start
    Route::post('ajax-icalender-import/{id}', 'CalendarController@icalendarImport');
    Route::get('icalendar/synchronization/{id}', 'CalendarController@icalendarSynchronization');
    //iCalendar routes end
    Route::post('currency-symbol', 'PropertyController@currencySymbol');
    Route::match(['get', 'post'], 'payments/book/{id?}', 'PaymentController@index');
    Route::post('payments/create_booking', 'PaymentController@createBooking');

	//TEST HYPERPAY
    Route::get('payments/test', 'PaymentController@testpay');
    Route::get('payments/checkout', 'PaymentController@checkout_hyperpay');
    Route::get('payments/paymentform-hyperpay', 'PaymentController@paymentform_hyperpay');
    Route::get('payments/callback-hyperpay', 'PaymentController@callback_hyperpay')->name('hyperpay-callback');
    Route::get('payments/check-status', 'PaymentController@checkstatus_hyperpay');
    Route::get('payments/data-store', 'PaymentController@data_store_ajax')->name('data_store');

    Route::get('payments/success', 'PaymentController@callback')->name('paymentCallback');
    Route::get('payments/cancel', 'PaymentController@cancel')->name('paymentCancel');
    Route::get('payments/stripe', 'PaymentController@stripePayment');
    Route::post('payments/stripe-request', 'PaymentController@stripeRequest');
    Route::match(['get', 'post'], 'payments/bank-payment', 'PaymentController@bankPayment');
    Route::get('booking/{id}', 'BookingController@index')->where('id', '[0-9]+');
    Route::get('booking_payment/{id}', 'BookingController@requestPayment')->where('id', '[0-9]+');
    Route::get('booking/requested', 'BookingController@requested');
    Route::get('booking/failed', 'BookingController@failed');
    Route::get('booking/itinerary_friends', 'BookingController@requested');
    Route::post('booking/accept/{id}', 'BookingController@accept');
    Route::post('booking/decline/{id}', 'BookingController@decline');
    Route::get('booking/expire/{id}', 'BookingController@expire');
    Route::match(['get', 'post'], 'my-bookings', 'BookingController@myBookings');
    Route::post('booking/host_cancel', 'BookingController@hostCancel');
    Route::match(['get', 'post'], 'trips/active', 'TripsController@myTrips');
    Route::get('booking/receipt', 'TripsController@receipt');
    Route::post('trips/guest_cancel', 'TripsController@guestCancel');

    // Messaging
    Route::match(['get', 'post'], 'inbox', 'InboxController@index');

	Route::match(['get', 'post'], 'window/{id}', 'InboxController@window');
    Route::post('messaging/booking/', 'InboxController@message');
    Route::post('messaging/reply/', 'InboxController@messageReply');

    Route::match(['get', 'post'], 'users/account-preferences', 'UserController@accountPreferences');
    Route::get('users/account_delete/{id}', 'UserController@accountDelete');
    Route::get('users/account_default/{id}', 'UserController@accountDefault');
    Route::get('users/transaction-history', 'UserController@transactionHistory');
    Route::post('users/account_transaction_history', 'UserController@getCompletedTransaction');
	// for customer payout settings
	Route::match(['GET', 'POST'], 'users/payout', 'PayoutController@index');
	Route::match(['GET', 'POST'], 'users/payout/setting', 'PayoutController@setting');
	Route::match(['GET', 'POST'], 'users/payout/edit-payout/', 'PayoutController@edit');
	Route::match(['GET', 'POST'], 'users/payout/delete-payout/{id}', 'PayoutController@delete');

	// for payout request
	Route::match(['GET', 'POST'], 'users/payout-list', 'PayoutController@payoutList');
	Route::match(['GET', 'POST'], 'users/payout/success', 'PayoutController@success');

    Route::match(['get', 'post'], 'users/security', 'UserController@security');
    Route::get('logout', function()
	{
		Auth::logout();
        Session::flush();
		return Redirect::to('login');
	});
});

//for exporting iCalendar
Route::get('icalender/export/{id}', 'CalendarController@icalendarExport');
Route::post('admin/authenticate', 'Admin\AdminController@authenticate');
Route::get('{name}', 'HomeController@staticPages');
Route::post('duplicate-phone-number-check', 'UserController@duplicatePhoneNumberCheck');
Route::post('duplicate-phone-number-check-for-existing-customer', 'UserController@duplicatePhoneNumberCheckForExistingCustomer');
Route::match(['GET', 'POST'], 'admin/settings/sms', 'Admin\SettingsController@smsSettings');
Route::match(['get', 'post'],'upload_image','Admin\PagesController@uploadImage')->name('upload');

Route::prefix('google')->name('google.')->group( function(){
	Route::get('login',[GoogleController::class, 'LoginwithGoogle'])->name('login');
	Route::any('callback',[GoogleController::class, 'callbackfromGoogle'])->name('callback');
});


// Route::get('data/users_verification', 'HomeController@user_verification_entries');
// Route::get('data/users_wallet', 'HomeController@user_wallet_entries');
// Route::get('dataentry/users', 'HomeController@data_insert_users');
// Route::get('dataentry/properties', 'HomeController@data_insert_properties');

// Route::get('dataentry/images/properties', 'HomeController@images_insert_properties');

// Route::get('/auth/github/redirect', 'SocialController@githubredirect');

app/Models/Admin.php
<?php

/**
 * Admin Model
 *
 * Admin Model manages Admin operation.
 *
 * @category   Admin
 * @package    darent
 * @author     Techvillage Dev Team
 * @copyright  2020 Techvillage
 * @license
 * @version    2.7
 * @link       http://techvill.net
 * @since      Version 1.3
 * @deprecated None
 */

namespace App\Models;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use DB;

class Admin extends Model implements AuthenticatableContract, CanResetPasswordContract
{
    use Authenticatable, CanResetPassword;

    protected $table    = 'admin';

    protected $fillable = ['username', 'email', 'password'];

    protected $hidden   = ['password', 'remember_token'];

    public function getProfileSrcAttribute()
    {
        if ($this->attributes['profile_image'] == '') {
            $src = url('public/images/user_pic.jpg');
        } else {
            $src = url('public/images/profile/'.$this->attributes['id'].'/'.$this->attributes['profile_image']);
        }

        return $src;
    }
}

app/Http/Controllers/Api/TripsController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Helpers\Common;


use View;
use DateTime;
use Auth;
use DB;
use Session;
use Carbon\Carbon;

use App\Models\{
    Bookings,
    BookingDetails,
    Messages,
    Penalty,
    Payouts,
    Properties,
    PayoutPenalties,
    PropertyDates,
    PropertyFees,
    Settings
};

class TripsController extends Controller
{
    private $helper;

    public function __construct()
    {
        $this->helper = new Common;
    }
    public function myTrips(Request $request)
    {
        switch ($request->status) {
            case 'Expired':
                $params  = [['created_at', '<', Carbon::yesterday()], ['status', '!=', 'Accepted']];
                break;
            case 'Current':
                $params  = [['start_date', '<=', date('Y-m-d')], ['end_date', '>=', date('Y-m-d')],['status', 'Accepted']];
                break;
            case 'Upcoming':
                $params  = [['start_date', '>', date('Y-m-d')], ['status', 'Accepted']];
                break;
            case 'Completed':
                $params  = [['end_date', '<', date('Y-m-d')],['status', 'Accepted']];
                break;
            case 'Pending':
                $params           = [['created_at', '>', Carbon::yesterday()], ['status', $request->status]];
                break;
            case 'Unpaid':
                $params           = [['created_at', '>', Carbon::yesterday()], ['status', $request->status]];
                break;
            default:
                $params           = [];
                break;
        }
        $data['yesterday'] = Carbon::yesterday();
        $data['status']    = $request->status;
        $data['bookings']  = Bookings::with('host','properties')
            ->where('user_id', Auth::user()->id)
            ->where($params)->orderBy('id', 'desc')
            ->paginate(Session::get('row_per_page'));

            return response()->json(['message'=>'Success','data'=>$data],200);

    }
}

resources/views/trips/active.blade.php
@extends('template')

@section('main')
    <div class="">
        <div class="row m-0">
            @include('users.sidebar')
            <div class="col-lg-10">
                <div class="main-panel">
                    <div class="container-fluid min-height">
                        <div class="row">
                            <div class="col-md-12 p-0 mb-3">
                                <div class="list-bacground mt-4 rounded-3 p-4 border">
                                    <span class="text-18 pt-4 pb-4 font-weight-700 font-sm">
                                        {{ trans('messages.users_dashboard.my_trips') }}
                                    </span>

                                    <div class="float-right">
                                        <div class="d-flex">
                                            <div class="pr-4 pd-left-rtl">
                                                <span
                                                    class="text-14 pt-2 pb-2 font-weight-700">{{ trans('messages.users_dashboard.sort_by') }}</span>
                                            </div>

                                            <div>
                                                <form action="{{ url('/trips/active') }}" method="POST" id="my-trip-form">
                                                    {{ csrf_field() }}
                                                    <select class="form-control room-list-status text-14 minus-mt-6"
                                                        name="status" id="trip_select">
                                                        <option value="All"
                                                            {{ $status == 'All' ? ' selected="selected"' : '' }}>All
                                                        </option>
                                                        <option value="Current"
                                                            {{ $status == 'Current' ? ' selected="selected"' : '' }}>Current
                                                        </option>
                                                        <option value="Upcoming"
                                                            {{ $status == 'Upcoming' ? ' selected="selected"' : '' }}>
                                                            Upcoming</option>
                                                        <option value="Pending"
                                                            {{ $status == 'Pending' ? ' selected="selected"' : '' }}>Pending
                                                        </option>
                                                        <option value="Completed"
                                                            {{ $status == 'Completed' ? ' selected="selected"' : '' }}>
                                                            Completed</option>
                                                        <option value="Expired"
                                                            {{ $status == 'Expired' ? ' selected="selected"' : '' }}>Expired
                                                        </option>
                                                    </select>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        @if (Session::has('message'))
                            <div class="alert alert-success text-center" role="alert" id="alert">
                                <span id="messages">{{ Session::get('message') }}</span>
                            </div>
                        @endif
                        @forelse($bookings as $booking)
                            <?php
                            $bookingStatus = $booking->status;
                            if ($booking->created_at < $yesterday && $booking->status != 'Accepted') {
                                $bookingStatus = 'Expired';
                            } elseif ($booking->status == 'Pending' && $booking->payment_method_id == 4) {
                                $bookingStatus = 'Processing';
                            }
                            ?>

                            <div class="row border border p-2 rounded-3 mt-4 custom-shadow">
                                <div class="col-xl-4 col-lg-4 col-md-3 col-sm-12 p-2">
                                    <div class="img-event cust-booking-img">
                                        <a href="{{ url('/') }}/properties/{{ $booking->properties->slug }}">
                                            <img class="room-image-container200 rounded"
                                                src="{{ $booking->properties->cover_photo }}" alt="cover_photo">
                                        </a>
                                    </div>
                                </div>
                                <div class="col-xl-6 col-lg-5 col-md-6 col-sm-8 pl-2 pd-right-rtl">
                                    <div class="d-flex justify-content-between align-items-center h-100">
                                        <div class="cust-booking-content text-right-rtl">
                                            <a href="{{ url('/') }}/properties/{{ $booking->properties->slug }}">
                                                <p
                                                    class="mb-1 text-18 text-color font-weight-700 text-color-hover pr-2 mb-3">
                                                    {{ $booking->properties->name }} </p>
                                            </a>
                                            <p class="text-14 mb-3">
                                                <i class="fas fa-map-marker-alt"></i>
                                                {{ $booking->properties->property_address->address_line_1 }}
                                            </p>
                                            <p class="text-14 mt-3">
                                                <i class="fas fa-calendar"></i>
                                                {{ date(' M d, Y', strtotime($booking->start_date)) }} -
                                                {{ date(' M d, Y', strtotime($booking->end_date)) }}
                                            </p>
                                            <p class="text-14 mt-3">
                                                @if ($booking->status == 'Accepted')
                                                    <span>
                                                        <a
                                                            href="{{ url('/') }}/booking/receipt?code={{ $booking->code }}">
                                                            <i class="fas fa-receipt"></i>
                                                            {{ trans('messages.trips_active.view_receipt') }}
                                                        </a>
                                                    </span>
                                                @elseif($booking->status == 'Processing' && $booking->payment_method_id != 4)
                                                    <span>
                                                        <a class="btn vbtn-outline-success text-14 font-weight-700 pl-4 pr-4 pt-3 pb-3 mt-4"
                                                            href="{{ url('/') }}/booking_payment/{{ $booking->id }}">
                                                            <i class="fab fa-cc-amazon-pay"></i> Make
                                                            {{ trans('messages.payment.payment') }}
                                                        </a>
                                                    </span>
                                                @endif
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div
                                    class="col-xl-2 col-lg-3 col-md-3 col-2 col-sm-4 col-12 border-left bd-l-remove bd-right-rtl">
                                    <div class="custom-booking-user">
                                        <div class="custom-booking-user-inner">
                                            <div class='img-round'>
                                                <a href="{{ url('/') }}/users/show/{{ $booking->host_id }}">
                                                    <img src="{{ $booking->host->profile_src }}"
                                                        alt="{{ $booking->host->first_name }}"
                                                        class="rounded-circle img-70x70">
                                                </a>
                                            </div>
                                            <div class="custom-booking-user-detail">
                                                <p class="text-center font-weight-700">
                                                    <a href="{{ url('/') }}/users/show/{{ $booking->host_id }}"
                                                        class="text-color text-color-hover">
                                                        {{ $booking->host->first_name }}
                                                    </a>
                                                </p>
                                                <span
                                                    class="badge vbadge-success text-13 mt-3 p-2 {{ $bookingStatus }}">{{ $bookingStatus }}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        @empty
                            <div class="row jutify-content-center position-center w-100 p-4 mt-4 ">
                                <div class="text-center w-100">
                                    <img src="{{ url('public/img/unnamed.png') }}" alt="notfound" class="img-fluid">
                                    <p class="text-center"> {{ trans('messages.message.empty_tripts') }} </p>
                                </div>
                            </div>
                        @endforelse

                        <div class="row justify-content-between overflow-auto pb-3 mt-4 mb-5">
                            {{ $bookings->appends(request()->except('page'))->links('paginate') }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@stop
@push('scripts')
    <script type="text/javascript">
        $(document).on('change', '#trip_select', function() {

            $("#my-trip-form").trigger("submit");

        });
    </script>
@endpush

resources/views/trips/receipt.blade.php
@extends('template')

@section('main')

<div class="container margin-top-85 p-0 mb-5 min-height">
  <div class="panel-body text-success">
   <h6 class="text-16">{{trans('messages.trips_receipt.receipt')}} # {{ $booking->id }}</h6>
 </div>
 <div class="card">
  <div class="card-header pt-3 pb-4">
    <strong class="font-weight-700">{{trans('messages.trips_receipt.customer_receipt')}}</strong>
    <span class="float-right"> <strong class="font-weight-700">{{trans('messages.trips_receipt.confirmation_code')}} :</strong> {{ $booking->code }}</span>
  </div>

  <div class="card-body pt-0 pb-0 pl-4 pr-4">
    <div class="row mb-4 mt-5">
      <div class="col-md-6 l-pad-none p-0">
       <img src="{{@$logo}}">
     </div>

     <div class="col-md-6 print-div text-right p-0" id="print-div">
      <a href="#" onclick="print_receipt()" class="btn vbtn-outline-success text-14 font-weight-700 pt-2 pb-2 mt-2 pl-3 pr-4 button">PDF</a>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6 col-sm-6 col-xs-12 mt-3 ow rpt pl-0">
      <div class="p-0">
        <span> <strong class="font-weight-700 text-18">{{trans('messages.trips_receipt.name')}} :</strong> {{ $booking->users->full_name }}</span>
      </div>
    </div>
    <div class="col-md-6 text-right pt-4 pr-0">
      <h4></h4>
    </div>
  </div>

  <div class="row rpt border pt-3 mb-5 mt-2">
    <div class="col-md-3 col-sm-3 col-xs-12"><!-- card pt-4 mb-5 mt-2 rounded-3 -->
      <h4 class="margin-top20"><strong>{{trans('messages.trips_receipt.accommodatoin_address')}}</strong></h4>
      <h5 class="margin-top20"><p class="text-lead">
        <strong>{{ @$booking->properties->name }}</strong>
      </p>
      <p class="text-lead">{{ @$booking->properties->property_address->address_line_1 }}<br>{{ @$booking->properties->property_address->city }}, {{ @$booking->properties->property_address->state }} {{ @$booking->properties->property_address->postal_code }}<br>{{ @$booking->properties->property_address->country_name }}<br></h5>
      </div>
      <div class="col-md-3 col-sm-3 col-xs-12">
        <h4><strong>{{trans('messages.trips_receipt.travel_destination')}}</strong></h4>
        <h5 class="margin-top20">{{ @$booking->properties->property_address->city }}</h5>
        <h4 class="margin-top20"><strong>{{trans('messages.trips_receipt.accommodation_host')}}</strong></h4>
        <h5 class="margin-top20">{{ @$booking->properties->users->full_name }}</h5>
      </div>

      <div class="col-md-3 col-sm-3 col-xs-12">
        <h4><strong>{{trans('messages.trips_receipt.duration')}}</strong></h4>
        <h5 class="margin-top20">{{ $booking->total_night }} {{trans('messages.trips_receipt.night')}}</h5>
        <h4 class="margin-top20"><strong>{{trans('messages.trips_receipt.check_in')}}</strong></h4>
        <h5 class="margin-top20">{{ $booking->startdate_dmy }}<br>{{trans('messages.trips_receipt.flexible_check_time')}}</h5>
      </div>

      <div class="col-md-3 col-sm-3 col-xs-12">
        <h4><strong>{{trans('messages.trips_receipt.accommodation_type')}}</strong></h4>
        <h5 class="margin-top20">{{ @$booking->properties->property_type_name }}</h5>
        <h4 class="margin-top20"><strong>{{trans('messages.trips_receipt.check_out')}}</strong></h4>
        <h5 class="margin-top20">{{ $booking->enddate_dmy }}<br>{{trans('messages.trips_receipt.flexible_check_out')}}</h5>
      </div>
    </div>

    <div class="table-responsive mt-3">
      <table class="table table-bordered table-hover p-0 m-0">
        <thead class="thead-dark">
          <tr>
            <th colspan="6">{{trans('messages.trips_receipt.booking_charge')}}</th>
          </tr>
        </thead>
        <tbody class="border">
          @if($date_price)
            @foreach($date_price as $datePrice )
              <tr>
                <td>{{ onlyFormat($datePrice->date) }}</td>
                <td class="text-right pr-4">{!! $booking->currency->symbol.$datePrice->price !!}  </td>
              </tr>
            @endforeach
          @endif
          <tr>
            <td>{!! $booking->currency->symbol.$booking->per_night !!} x {{ $booking->total_night }} {{trans('messages.trips_receipt.night')}}</td>
            <td class="text-right pr-4">{!! $booking->currency->symbol.$booking->per_night * $booking->total_night !!}</td>
          </tr>
          @if($booking->guest_charge)
          <tr>
            <td class=""> {{trans('messages.trips_receipt.additional_guest_fee')}} </td>
            <td class="text-right pr-4">{!! $booking->currency->symbol.$booking->guest_charge !!}</td>
          </tr>
          @endif
          @if($booking->cleaning_charge)
          <tr>
            <td class=""> {{trans('messages.trips_receipt.cleaning_fee')}} </td>
            <td class="text-right pr-4">{!! $booking->currency->symbol.$booking->cleaning_charge !!}</td>
          </tr>
          @endif
          @if($booking->security_money)
          <tr>
            <td class=""> {{trans('messages.trips_receipt.security_fee')}} </td>
            <td class="text-right pr-4">{!! $booking->currency->symbol.$booking->security_money !!}</td>
          </tr>
          @endif
          @if($booking->iva_tax)
          <tr>
            <td class=""> I.V.A Tax  </td>
            <td class="text-right pr-4">{!! $booking->currency->symbol.$booking->iva_tax !!}</td>
          </tr>
          @endif
           @if($booking->accomodation_tax)
          <tr>
            <td class="">Accomadation Tax </td>
            <td class="text-right pr-4">{!! $booking->currency->symbol.$booking->accomodation_tax !!}</td>
          </tr>
          @endif
          <tr>
            <td>{{ $site_name }} {{trans('messages.trips_receipt.service_fee')}}</td>
            <td class="text-right pr-4">{!! $booking->currency->symbol.$booking->service_charge !!}</td>
          </tr>
          <tr>
            <td>{{trans('messages.trips_receipt.total')}}</td>
            <td class="text-right pr-4">{!! $booking->currency->symbol.$booking->total !!}</td>
          </tr>
        </tbody>
      </table>
    </div>

    <div class="row">
      <div class="col-lg-3 col-sm-5 ml-auto pr-0">
        <table class="table table-clear">
          <tbody>
            <tr>
              <td class="left">
                <strong>{{trans('messages.trips_receipt.payment_received')}}:{{ $booking->receipt_date }}</strong>
              </td>
              <td class="text-right pr-4"> {!! $booking->transaction_id ?  $booking->currency->symbol.$booking->total: 0 !!}</td>
            </tr>

          </tbody>
        </table>

      </div>

    </div>

  </div>
</div>
</div>

<script ttype="text/javascript">
  function print_receipt()
  {
    document.getElementById("print-div").classList.add("d-none");
    document.getElementById("footer").classList.add("d-none");
    window.print();

     $("#print-div").removeClass("d-none");
  }

</script>
@stop